### ISSUE TITLE
Dlib execution on intel movidius

### ISSUE THREAD

**Issue by danishnazir** [TechBubbleTechnologies/IoT-JumpWay-Intel-Examples#3]
Hi there!
can you explain that how you ported dlib model to intel movidius chip? or you are not running dlib model at movidius chip?
regards

**Comment by AdamMiltonBarker** [comment]
Hi, I have not done any modification, as far as I am aware at this time dlib does not run on the Movidius but I could be wrong.

**Comment by danishnazir** [comment]
i see! thanks

**Comment by AdamMiltonBarker** [comment]
No problem
